version: '2.1'

orbs:
  windows: circleci/windows@2.4.0

executors:
  python:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: 1

jobs:
  test-app:
    executor: python
    steps:
      - checkout
      - run:
          name: Changing file permissiosn for later steps
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          name: 'Restoring cache'
          keys:
            - v1-twitter-image-dl-{{ checksum "./Pipfile.lock" }}
            - v1-twitter-image-dl
      - run:
          name: Installing dependencies
          command: |
            pip install pipenv
            pipenv install -d
      - run:
          name: Executing tests
          command: |
            mkdir ./testdata/download
            pipenv run test
      - save_cache:
          name: Saving dependency cache
          key: v1-twitter-image-dl-{{ checksum "./Pipfile.lock" }}
          paths:
            - "./.venv"
            - "/usr/local/bin"
            - "/usr/local/bin/python3.7/site-packages"

  build:
    executor: windows/default
    steps:
      - checkout
      - run:
          name:
          command: |
            .\build\build.bat

workflows:
  version: '2'
  test-and-distribute:
    jobs:
      # - test-app
      - build
