version: '2.1'

orbs:
  windows: circleci/windows@2.4.0
  s3: circleci/aws-s3@1.0.16

executors:
  python:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: 1

jobs:
  test-app:
    executor: python
    steps:
      - checkout
      - run:
          name: Changing file permissiosn for later steps
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          name: 'Restoring cache'
          keys:
            - v1-twitter-image-dl-{{ checksum "./Pipfile.lock" }}
            - v1-twitter-image-dl
      - run:
          name: Installing dependencies
          command: |
            pip install pipenv
            pipenv install -d
      - run:
          name: Executing tests
          command: |
            mkdir ./testdata/download
            pipenv run test
      - save_cache:
          name: Saving dependency cache
          key: v1-twitter-image-dl-{{ checksum "./Pipfile.lock" }}
          paths:
            - "./.venv"
            - "/usr/local/bin"
            - "/usr/local/bin/python3.7/site-packages"

  build:
    executor: windows/default
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - restore_cache:
          name: Restoring dependency cache
          keys:
            - v2-twitter-image-dl-windows-{{ checksum "./Pipfile.lock" }}
            - v2-twitter-image-dl-windows-
      - run:
          name: Installing dependencies
          command: |
            pip install pipenv
            pipenv install -d
      - run:
          name: Building executable
          command: |
            .\build\build.bat
      - run:
          name: Creating archive of built files
          command: |
            $ProgressPreference = "SilentlyContinue"
            Compress-Archive -Path .\dist\gui, .\dist\twitter_image_dl -DestinationPath .\twitter_image_dl.zip
      - persist_to_workspace:
          root: .
          paths:
            - twitter_image_dl.zip
      - save_cache:
          name: Saving dependency cache
          key: v2-twitter-image-dl-windows-{{ checksum "./Pipfile.lock" }}
          paths:
            - .\.venv

  distribute:
    executor: python
    steps:
      - attach_workspace:
          at: ./workspace
      - s3/copy:
          from: ./workspace/twitter_image_dl.zip
          to: $S3_URL/twitter_image_dl.zip
          arguments: |
            --acl public read
          overwrite: true

workflows:
  version: '2'
  test-and-distribute:
    jobs:
      # - test-app
      - build
      - distribute:
          requires:
            - build
          context: AWS
